CXX := /usr/bin/g++
CPPFLAGS := -I..
CXXFLAGS := -Wall -Wextra -pedantic-errors -std=c++0x -O2 -pthread

concurrent_string : ConcurrentWrapper.h ../Queue/Queue.h

concurrent_string2 : ConcurrentWrapper.h ../Queue/Queue.h

