#CC = /opt/local/bin/gcc-mp-4.8
#CXX = /opt/local/bin/g++-mp-4.8
#CXX = /opt/local/bin/clang++-mp-3.4
#CC = /opt/local/bin/clang-mp-3.3
CXXFLAGS += -Wall -Wextra -Wconversion -Wno-missing-field-initializers -pedantic-errors -std=c++11 -pthread -O2
CFLAGS += -Wall -Wextra -Wconversion -Wno-missing-field-initializers -pedantic-errors -pthread -O2

