#CXX := /usr/bin/g++-4.8
CPPFLAGS := -I..
CXXFLAGS := -Wall -Wextra -pedantic-errors -std=c++11 -O2 -pthread

concurrent_string : Concurrent.h ../Queue/Queue.h

concurrent_string2 : Concurrent.h ../Queue/Queue.h

concurrent_vector : Concurrent.h ../Queue/Queue.h
